package cn.database.bean.impl;
// Generated 2017-5-23 16:31:18 by Hibernate Tools 4.3.1


import cn.database.bean.get.IAllowanceGET;
import cn.database.bean.set.IAllowanceSET;
import cn.database.bean.interf.IAllowance;
import cn.database.core.DateUtil;
import java.util.Date;

/**
 * Allowance generated by hbm2java
 */
public class Allowance implements java.io.Serializable ,IAllowance, IAllowanceSET,IAllowanceGET{


     private Integer id;
     private Employee employee;
     private Date day;
     private Double workHours;
     private String type;
     private Double perk;

    public Allowance() {
    }

    public Allowance(Employee employee, Date day, Double workHours, String type, Double perk) {
       this.employee = employee;
       this.day = day;
       this.workHours = workHours;
       this.type = type;
       this.perk = perk;
    }
   
    @Override
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
     @Override
    public String getEmployeeName() {
      return  employee==null?"":employee.getName();
    }

     @Override
    public String getDateString() {
       return day==null?"":DateUtil.parseDate(day);
    }

    public Employee getEmployee() {
        return this.employee;
    }
    
    @Override
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    public Date getDay() {
        return this.day;
    }
    
    @Override
    public void setDay(Date day) {
        this.day = day;
    }
    @Override
    public Double getWorkHours() {
        return this.workHours;
    }
    
    @Override
    public void setWorkHours(Double workHours) {
        this.workHours = workHours;
    }
    @Override
    public String getType() {
        return this.type;
    }
    
    @Override
    public void setType(String type) {
        this.type = type;
    }
    @Override
    public Double getPerk() {
        return this.perk;
    }
    
    @Override
    public void setPerk(Double perk) {
        this.perk = perk;
    }

   
   
    @Override
    public Date getDate() {
       return day;
    }

   




}


