package cn.database.bean.impl;
// Generated 2017-5-23 22:28:33 by Hibernate Tools 4.3.1

import cn.database.bean.get.IAnnualBonusGET;
import cn.database.bean.set.IAnnualBonusSET;
import cn.database.bean.interf.IAnnualBonus;




/**
 * AnnualBonus generated by hbm2java
 */
public class AnnualBonus  implements java.io.Serializable, IAnnualBonus, IAnnualBonusSET ,IAnnualBonusGET{


     private Integer id;
     private Employee employee;
     private String year;
     private Double award;

    public AnnualBonus() {
    }

	
    public AnnualBonus(int id) {
        this.id = id;
    }
    public AnnualBonus(int id, Employee employee, String year, Double award) {
       this.id = id;
       this.employee = employee;
       this.year = year;
       this.award = award;
    }
   
    @Override
    public Integer getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    @Override
    public void setEmployee(Employee employee) {
        this.employee = employee;
    } 
    @Override
    public String getYear() {
        return this.year;
    }
    
    @Override
    public void setYear(String year) {
        this.year = year;
    }
    @Override
    public Double getAward() {
        return this.award;
    }
    
    @Override
    public void setAward(Double award) {
        this.award = award;
    }

    @Override
    public String getEmployeeName() {
         return  employee==null?"":employee.getName();
    }




}


