package cn.database.bean.impl;


import cn.database.bean.get.IAttendanceGET;
import cn.database.bean.set.IAttendanceSET;
import cn.database.bean.interf.IAttendance;
import cn.database.core.DateUtil;
import java.util.Date;


/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements IAttendance , java.io.Serializable, IAttendanceSET  , IAttendanceGET{


     private Integer id;
     private Employee employee;
     private String month;
     private Integer late;
     private Integer absence;
     private Integer sign;

    public Attendance() {
    }

    public Attendance(Employee employee, String month, Integer late, Integer absence, Integer sign) {
       this.employee = employee;
       this.month = month;
       this.late = late;
       this.absence = absence;
       this.sign = sign;
    }
   
    @Override
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    @Override
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
     @Override
    public String getEmployeeName() {
        return employee==null?"":employee.getName();
    }

    @Override    
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    @Override
    public Integer getLate() {
        return this.late;
    }
    
    @Override
    public void setLate(Integer late) {
        this.late = late;
    }
    @Override
    public Integer getAbsence() {
        return this.absence;
    }
    
    @Override
    public void setAbsence(Integer absence) {
        this.absence = absence;
    }
    @Override
    public Integer getSign() {
        return this.sign;
    }
    
    @Override
    public void setSign(Integer sign) {
        this.sign = sign;
    }

    @Override
    public Date getDate() {
       return DateUtil.parseMonth(month);
    }

    @Override
    public void setMonth(Date month) {
        this.month=DateUtil.parseMonth(month);
    }

  

   



}


