package cn.database.bean.impl;
// Generated 2017-5-23 16:31:18 by Hibernate Tools 4.3.1


import cn.database.bean.get.IDepartmentGET;
import cn.database.bean.interf.IDepartment;
import java.util.HashSet;
import java.util.Set;
import cn.database.bean.set.IDepartmentSET;

/**
 * Department generated by hbm2java
 */
public class Department  implements IDepartment,java.io.Serializable, IDepartmentSET,IDepartmentGET{



     private Integer id;
     private String name;
     private Set employees = new HashSet(0);

    public Department() {
    }

    public Department(String name, Set employees) {
       this.name = name;
       this.employees = employees;
    }
   
    @Override
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Override
    public String getName() {
        return this.name;
    }
    
    @Override
    public void setName(String name) {
        this.name = name;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }


    @Override
    public String toString() {
        return id + " " + name ;
    }


}


