package cn.database.bean.impl;
// Generated 2017-5-23 16:31:18 by Hibernate Tools 4.3.1

import cn.database.bean.get.IEmployeeGET;
import cn.database.bean.set.IEmployeeSET;
import cn.database.bean.interf.IEmployee;
import cn.database.bean.other.Sex;
import cn.database.core.DateUtil;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable, IEmployee, IEmployeeSET, IEmployeeGET {

    private Integer id;
    private Department department;
    private Joblevel joblevel;
    private String name;
    private Date birthday;
    private String sex;
    private Date hireTime;
    private Set wages = new HashSet(0);
    private Set allowances = new HashSet(0);
    private Set attendances = new HashSet(0);

    public Employee() {
    }

    public Employee(Department department, Joblevel joblevel, String name, Date birthday, String sex, Date hireTime, Set wages, Set allowances, Set attendances) {
        this.department = department;
        this.joblevel = joblevel;
        this.name = name;
        this.birthday = birthday;
        this.sex = sex;
        this.hireTime = hireTime;
        this.wages = wages;
        this.allowances = allowances;
        this.attendances = attendances;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Department getDepartment() {
        return this.department;
    }

    @Override
    public void setDepartment(Department department) {
        this.department = department;
    }

    public Joblevel getJoblevel() {
        return this.joblevel;
    }

    @Override
    public void setJoblevel(Joblevel joblevel) {
        this.joblevel = joblevel;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    @Override
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getHireTime() {
        return this.hireTime;
    }

    @Override
    public void setHireTime(Date hireTime) {
        this.hireTime = hireTime;
    }

    public Set getWages() {
        return this.wages;
    }

    public void setWages(Set wages) {
        this.wages = wages;
    }

    public Set getAllowances() {
        return this.allowances;
    }

    public void setAllowances(Set allowances) {
        this.allowances = allowances;
    }

    public Set getAttendances() {
        return this.attendances;
    }

    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }

    @Override
    public String getBirthDayString() {
        return birthday == null ? "" : DateUtil.parseDate(birthday);
    }

    @Override
    public String getSexString() {
        return sex == null ? "" : Sex.getName(sex);
    }

    @Override
    public String getDepartmentName() {
        return department == null ? "" : department.getName();
    }

    @Override
    public String getHireTimeString() {
        return hireTime == null ? "" : DateUtil.parseDate(hireTime);
    }

    @Override
    public String getJobLevelString() {
        return joblevel == null ? "" : joblevel.getTypeName();
    }

    @Override
    public Date getDate() {
        return hireTime;
    }

    @Override
    public void setSex(Sex sex) {
        this.sex = sex == null ? null : sex.getValue();
    }

    @Override
    public Sex getSexSex() {
        return Sex.valueTo(sex);
    }

    @Override
    public String toString() {
        return id + " " + name ;
    }

}
