package cn.database.bean.impl;
// Generated 2017-5-23 16:31:18 by Hibernate Tools 4.3.1


import cn.database.bean.get.IJoblevelGET;
import cn.database.bean.set.IJobLevelSET;
import java.util.HashSet;
import java.util.Set;
import cn.database.bean.interf.IJobLevel;

/**
 * Joblevel generated by hbm2java
 */
public class Joblevel  implements java.io.Serializable, IJobLevel, IJobLevelSET , IJoblevelGET{


     private Integer id;
     private String typeName;
     private Integer grade;
     private Double salary;
     private Set employees = new HashSet(0);

    public Joblevel() {
    }

    public Joblevel(String typeName, Integer grade, Double salary, Set employees) {
       this.typeName = typeName;
       this.grade = grade;
       this.salary = salary;
       this.employees = employees;
    }
   
    @Override
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Override
    public String getTypeName() {
        return this.typeName;
    }
    
    @Override
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    @Override
    public Integer getGrade() {
        return this.grade;
    }
    
    @Override
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
    @Override
    public Double getSalary() {
        return this.salary;
    }
    
    @Override
    public void setSalary(Double salary) {
        this.salary = salary;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
   
    public void setEmployees(Set employees) {
        this.employees = employees;
    }

    @Override
    public String toString() {
        return  id + " " + typeName;
    }




}


